#!/bin/sh /etc/rc.common
# Copyright (C) 2017 Symid.COM

START=90

USE_PROCD=1

BASE_DIR=/usr/iot
SKYNET_DIR=$BASE_DIR/skynet
SKYNET_IOT_DIR=$SKYNET_DIR/iot

PM_BIN=process-monitor
SKYNET_BIN=$SKYNET_DIR/skynet
STARTUP_SH=$SKYNET_IOT_DIR/startup.sh

if [ -f /etc/os-release ]
then
	source /etc/os-release
	if [ -f $SKYNET_IOT_DIR/openwrt/$LEDE_ARCH/process-monitor ]
	then
		PM_BIN=$SKYNET_IOT_DIR/openwrt/$LEDE_ARCH/process-monitor
	fi
fi

start_service () {
	procd_open_instance
	procd_set_param env IOT_RUN_AS_DAEMON=1
	procd_set_param command "$PM_BIN" -M 2 -D "$SKYNET_DIR" -S "sh $STARTUP_SH $BASE_DIR" $SKYNET_BIN iot/config
	procd_set_param respawn
	procd_close_instance
}

