#!/bin/sh /etc/rc.common
# Copyright (C) 2017 Symid.COM

START=90

USE_PROCD=1
PROG=/mnt/process-monitor
WORK_DIR=/mnt/skynet
WORK_PROG=/mnt/skynet/skynet
WORK_STARTUP=/mnt/skynet/startup.sh

start_service () {
	procd_open_instance
	procd_set_param command "$PROG" -D "$WORK_DIR" -S "sh $WORK_STARTUP $WORK_DIR" $WORK_PROG iot/config
	procd_set_param respawn
	procd_close_instance
}

